# -*- coding: utf-8 -*-
"""CSE472.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svdfOXauTp_DImXp9RE4Sjvqde3PhCft
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

from pandas import read_csv
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

classifier1 = ["Claim", "Label"]
train = read_csv("train.csv", usecols=classifier1)

classifier2 = ["Claim"]
test = read_csv("test.csv", usecols=classifier2)

X=train["Claim"]
Y=train["Label"]
X_test_pred = test["Claim"]

x_train,x_test,y_train,y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

tfidf_vectorizer = TfidfVectorizer(stop_words= "english", strip_accents= "unicode")
X_test_pred =test["Claim"]

X_train=tfidf_vectorizer.fit_transform(x_train)
X_test=tfidf_vectorizer.transform(x_test)
X_test_pred = tfidf_vectorizer.transform(X_test_pred)

accuracy=[]
for i in range(1276,1277):
    classify = KNeighborsClassifier(n_neighbors = i).fit(X_train,y_train)
    y_pred = classify.predict(X_test)
    accuracy.append(accuracy_score(y_test, y_pred))
print(accuracy)

classify = KNeighborsClassifier(n_neighbors = 14)
classify.fit(X_train,y_train)
y_pred = classify.predict(X_test_pred)

print(y_pred)
id = []
for i in range(710):
  id.append(i+1)
result = pd.DataFrame({"Id":id,"Predicted":y_pred})
result.to_csv("submission.csv", index=False)